## Data Analyst
*they get the data: mine the oil, basic refining*

- SQL
- Developer - MNC
- Power BI - charts (visually)
- insights - charts

## Data Scientists
*they refine completely: mixing fuels, etc*

- excel
- Python - numpy, pandas
- scale - can handle million data easily
- scikit - data prediction
- matplot, seaborn  charts
- line by line (step) verification


In [2]:
import numpy as np

## numpy

- working with arrays
- work with 1D data
- performant (compared to normal pythin lists)
-  C language
-  statistical oriented - mean,median, mode
-  builing block for panda : which can handle 2D data

In [ ]:
marks1 = [90, 80, 20, 40] #create array: array: list --> array

print(marks1*2) #repeat operator


[90, 80, 20, 40, 90, 80, 20, 40]


In [3]:
marks2 = np.array([90, 80, 20, 40])
print(marks2 * 2)


[180 160  40  80]


In [ ]:
marks_dbl = [x * 2 for x in marks1]

print(marks_dbl)


[180, 160, 40, 80]


In [ ]:
np.ones(10) # identity matrix
np.ones(100)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10) # why np 0s?

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
5*np.ones(20)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [ ]:
#for a range of number
np.arange(10)
np.arange(1, 11)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1, 11, 2)


array([1, 3, 5, 7, 9])

## Operations
- multipy, division, addition, subtraction

In [ ]:
np.arange(1, 11) * 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(1, 11) + 2 #matrix addition


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
np.arange(1, 11) / 2


array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [21]:
np.arange(1, 11) - 2


array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
np.arange(1, 11) * np.arange(1, 11)


array([          1,           4,          27,         256,        3125,
             46656,      823543,    16777216,   387420489, 10000000000])

### Operatons between two arrays
- different sizes arise in an error

In [42]:
np.array([9, 2, 3]) * np.array([1, 2, 5])


array([ 9,  4, 15])

In [41]:
np.array([9, 2, 3]) ** np.array([1, 2, 5])


array([  9,   4, 243])

In [24]:
[9, 2, 3] + [1, 2, 5]


[9, 2, 3, 1, 2, 5]

## Boolean (matrix/mask)
- cant do operations on matrices of different sizes
- 

In [25]:
np.arange(1, 11) > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
first_ten_nums = np.arange(1, 11)
only_five_bm = first_ten_nums > 5
first_ten_nums[only_five_bm]

array([ 6,  7,  8,  9, 10])

In [ ]:
first_ten_nums = np.arange(1, 11)
#passing a matrix will do the filtering
first_ten_nums[first_ten_nums > 5]


array([ 6,  7,  8,  9, 10])

In [45]:
# 1 - 200 only even numbers, no skip
two_hundred = np.arange(1, 201)
print(two_hundred[two_hundred % 2 == 0])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [44]:
two_hundred = np.arange(2, 201, 2)
print(two_hundred)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [48]:
ages = np.random.randint(18, 60, 5)
ages[ages>25]
ages_list = ages.tolist()

In [49]:
%%time
ages_list


CPU times: total: 0 ns
Wall time: 196 μs


[56, 37, 19, 50, 25]