## Data Analyst
*they get the data: mine the oil, basic refining*

- SQL
- Developer - MNC
- Power BI - charts (visually)
- insights - charts

## Data Scientists
*they refine completely: mixing fuels, etc*

- excel
- Python - numpy, pandas
- scale - can handle million data easily
- scikit - data prediction
- matplot, seaborn  charts
- line by line (step) verification


In [2]:
import numpy as np

## numpy

- working with arrays
- work with 1D data
- performant (compared to normal pythin lists)
-  C language
-  statistical oriented - mean,median, mode
-  builing block for panda : which can handle 2D data

In [ ]:
marks1 = [90, 80, 20, 40] #create array: array: list --> array

print(marks1*2) #repeat operator


[90, 80, 20, 40, 90, 80, 20, 40]


In [3]:
marks2 = np.array([90, 80, 20, 40])
print(marks2 * 2)


[180 160  40  80]


In [ ]:
marks_dbl = [x * 2 for x in marks1]

print(marks_dbl)


[180, 160, 40, 80]


In [ ]:
np.ones(10) # identity matrix
np.ones(100)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10) # why np 0s?

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
5*np.ones(20)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [ ]:
#for a range of number
np.arange(10)
np.arange(1, 11)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1, 11, 2)


array([1, 3, 5, 7, 9])

## Operations
- multipy, division, addition, subtraction

In [ ]:
np.arange(1, 11) * 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(1, 11) + 2 #matrix addition


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
np.arange(1, 11) / 2


array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [21]:
np.arange(1, 11) - 2


array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
np.arange(1, 11) * np.arange(1, 11)


array([          1,           4,          27,         256,        3125,
             46656,      823543,    16777216,   387420489, 10000000000])

### Operatons between two arrays
- different sizes arise in an error

In [42]:
np.array([9, 2, 3]) * np.array([1, 2, 5])


array([ 9,  4, 15])

In [41]:
np.array([9, 2, 3]) ** np.array([1, 2, 5])


array([  9,   4, 243])

In [24]:
[9, 2, 3] + [1, 2, 5]


[9, 2, 3, 1, 2, 5]

## Boolean (matrix/mask)
- cant do operations on matrices of different sizes
- 

In [25]:
np.arange(1, 11) > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
first_ten_nums = np.arange(1, 11)
only_five_bm = first_ten_nums > 5
first_ten_nums[only_five_bm]

array([ 6,  7,  8,  9, 10])

In [ ]:
first_ten_nums = np.arange(1, 11)
#passing a matrix will do the filtering
first_ten_nums[first_ten_nums > 5]


array([ 6,  7,  8,  9, 10])

In [45]:
# 1 - 200 only even numbers, no skip
two_hundred = np.arange(1, 201)
print(two_hundred[two_hundred % 2 == 0])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [44]:
two_hundred = np.arange(2, 201, 2)
print(two_hundred)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [48]:
ages = np.random.randint(18, 60, 5)
ages[ages>25]
ages_list = ages.tolist()

In [49]:
%%time
ages_list


CPU times: total: 0 ns
Wall time: 196 μs


[56, 37, 19, 50, 25]

## statistical oriented - mean, mode, median, std

- mean --> verage
- mode --> most repeated number(most popular)
- median --> middle value in sorted array
- std --> how fr apart data is. average distance between mean and numbers

In [ ]:

import numpy as np

marks = np.random.randint(40, 100, 10)

print(marks)
print(marks.mean())
print(np.mean(marks))

[59 92 87 93 50 67 64 47 55 85]
69.9
69.9


In [5]:
print(np.median(marks))

65.5


In [6]:
print(np.sum(marks))


699


In [7]:
print(np.std(marks))

16.87275911047153


In [9]:
sixty_fours = np.ones(11)*64
print(sixty_fours)
np.mean(sixty_fours)

[64. 64. 64. 64. 64. 64. 64. 64. 64. 64. 64.]


np.float64(64.0)

### Task 1
At the every year tell me balance for 10 years
Clue: General formula
1102.5 -> 1000 +
[1050, 1102.5 ...., ]

In [ ]:
## task 1
def compound_interest(principal, rate, time):
    amount = principal * (pow((1 + rate / 100), time))
    interest = amount - principal
    return interest + principal

i = 0
value = 1000
output = []

while i < 10:
    value = compound_interest(value, 5, 1)
    output.append(value)
    i+=1

print(output)

## task 2

year_ten = compound_interest(1000, 5, 10)
print(year_ten)
year_one = compound_interest(1000, 5, 1)

diff = year_ten - year_one
print(diff)


[1050.0, 1102.5, 1157.625, 1215.5062500000001, 1276.2815625000003, 1340.0956406250004, 1407.1004226562504, 1477.455443789063, 1551.3282159785163, 1628.8946267774422]
1628.894626777442
578.894626777442


In [38]:
#task 1
interest = 1.05
amount = 1000
num_years = np.arange(1, 11)

balances = amount * (interest) ** num_years

#print(balances)
#print(amount * interest ** num_years)
#task 2
year_ten = balances[-1]
print(year_ten)

#task 3
difference = year_ten - 1000
percentage = difference /10
print(percentage)


1628.894626777442
62.8894626777442


## slicing

- index
- negative index
- range

## useful methods
- max, min - argmax, argmin
- unique, flip
- string methods

In [45]:
salaries = np.random.randint(1000, 4000, 10)
print(np.max(salaries))
print(np.min(salaries))
print(np.argmin(salaries))
print(np.argmax(salaries))


3544
1150
0
9


In [43]:
nums = np.random.randint(1, 4, 10)

print(np.unique(nums))

[1 2 3]


In [ ]:
hourly_visitors = np.array([468, 279, 73, 272, 406, 128, 302, 216, 140, 82])

print(f"Total visitors in the day: {np.sum(hourly_visitors)}")
#task 1.2
print(f"Peak hour: {np.argmax(hourly_visitors) + 1}")
#task 1.3
print(f"Average people visit: {round(np.mean(hourly_visitors))}")

Total visitors in the day: 2366
Peak hour: 1
Average people visit: 237


In [52]:
words = np.array(["hello", "world", "numpy"])

print(np.char.upper(words))
print(np.char.capitalize(words))

['HELLO' 'WORLD' 'NUMPY']
['Hello' 'World' 'Numpy']


## 

In [62]:
items = np.array(
    [
        " Apple",
        "banana ",
        "GRAPE",
        "cucumber",
        "Pineapple",
        " tomato ",
        "Orange",
        " lemon",
        "Kiwi ",
        "mango",
        "blueberry ",
        " raspberry"
    ]
)

#task 1.1
items = np.char.strip(items)

#task 1.2
items = np.char.lower(items)

#task 1.3
items = np.unique(items)

items

array(['apple', 'banana', 'blueberry', 'cucumber', 'grape', 'kiwi',
       'lemon', 'mango', 'orange', 'pineapple', 'raspberry', 'tomato'],
      dtype='<U10')